#!/usr/bin/env bash

# Description: Open new tmux window and preview all the image files in it.
#
# Dependencies: kitty, fzf, bat
#
# Limitation: breaks if a filename has newline in it
#
# Shell: POSIX compliant
# Author: Tri Pham

# IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}" # protect trailing \n
. "$(dirname "$0")"/.nnn-plugin-helper

# selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
echo $1
PWD=$PWD
selection="$PWD/$1"
[ -e "$selection" ] || {
	echo "plugin my_fzf_image_preview error: empty selection" >&2
	exit 1
}

# Open the file (works for a single file only)
entry="$(dirname "$selection")"
echo $entry

if [ -d "$entry" ]; then
	tmux set -g default-shell "/bin/bash" ;\
    tmux new-window -n "fzf-image-preview" -c "$entry" "find . -maxdepth 1 | sed 's/^..//' | fzf --ansi --preview='fzf-preview.sh {}' --bind ctrl-k:preview-page-up,ctrl-j:preview-page-down"
else
	echo >&2 "plugin my_fzf_image_preview error: not a directory"
fi
