#!/usr/bin/env sh

# Description: Regular mode:
#                Fuzzy find a file in directory subtree.
#                Opens in new tmux window.
#
#
# Dependencies: fd/find, fzf/skim, tmux
#
# Shell: POSIX compliant
# Author: Tri Pham

# shellcheck disable=SC1090,SC1091
. "$(dirname "$0")"/.nnn-plugin-helper
CTX=+

if type fzf >/dev/null 2>&1; then
    cmd="$FZF_DEFAULT_COMMAND"
    if type fd >/dev/null 2>&1; then
        [ -z "$cmd" ] && cmd="fd -t d 2>/dev/null"
    else
        [ -z "$cmd" ] && cmd="find . -type d 2>/dev/null"
    fi
    entry="$(eval "$cmd" | fzf -m)"
    # To show only the file name
    # entry=$(find . -type f 2>/dev/null | fzf --delimiter / --with-nth=-1 --tiebreak=begin --info=hidden)
elif type sk >/dev/null 2>&1; then
	entry=$(find . -type d 2>/dev/null | sk)
else
    exit 1
fi

# Check for picker mode
if [ "$3" ]; then
    if [ "$entry" ]; then
        case "$entry" in
            /*) fullpath="$entry" ;;
            *)  fullpath="$PWD/$entry" ;;
        esac
        if [ "-" = "$3" ]; then
            printf "%s\n" "$fullpath"
        else
            printf "%s\n" "$fullpath" > "$3"
        fi

        # Tell `nnn` to clear its internal selection
        printf "%s" "0p" > "$NNN_PIPE"
    fi

    exit 0
fi

# Open the selected folder in new tmux window
if [ -n "$entry" ]; then
    echo "**********************************************************"
    echo "> Selected folder: $entry\n"
    echo "Please choose the action to proceed:\n"
    echo "  1. Copy to clipboard"
    echo "  2. Open in new tmux window"
    echo "  3. Change to selected folder"
    read -r -p "Action: " ans
    case $ans in
        1)
            if type xsel >/dev/null 2>&1; then
               # Linux 
                xsel -d && echo "$entry" | tr '\0' '\n' | xsel -bi
            elif type xclip >/dev/null 2>&1; then
                # Linux
                tr '\0' '\n' < "$entry" | xclip -sel clip
            fi
            ;;
        2)
            tmux new-window -c "$entry";;
        3)
            if [ -n "$entry" ]; then
                if [ "$entry" = "." ] || { ! [ -d "$entry" ] && ! [ -f "$entry" ]; }; then
                    exit 0
                fi

                # Check if the selected path returned by fzf command is absolute
                case $entry in
                /*) nnn_cd "$entry" "$CTX" ;;
                *)
                    # Remove "./" prefix if it exists
                    sel="${sel#./}"

                    if [ "$PWD" = "/" ]; then
                        nnn_cd "/$entry" "$CTX"
                    else
                        nnn_cd "$PWD/$entry" "$CTX"
                    fi;;
                esac
            fi
            ;;
        *)
            exit;;
    esac
fi