#!/usr/bin/env bash

# Description: Open new tmux window and run lfrun (lf with image preview support).
#
# Dependencies: kitty, lf (with image preview support), tmux
#
# Limitation: breaks if a filename has newline in it
#
# Shell: POSIX compliant
# Author: Tri Pham

# IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}" # protect trailing \n
. "$(dirname "$0")"/.nnn-plugin-helper

# selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
echo $1
PWD=$PWD
selection="$PWD/$1"
[ -e "$selection" ] || {
	echo "plugin my_lfrun error: empty selection" >&2
	exit 1
}

# Open the file (works for a single file only)
entry="$(dirname "$selection")"
echo $entry

if [ -d "$entry" ]; then
  tmux new-window -c "$entry" "lfrun"
else
	echo >&2 "plugin my_lfrun error: not a directory"
fi
