#!/usr/bin/env bash

# Description: Regular mode:
#                Fuzzy find a directory in zoxide database sand
#                display a list of actions for user to choose.
#
#
# Dependencies: fzf/skim, tmux, zoxide
#
# Shell: POSIX compliant
# Author: Tri Pham

# shellcheck disable=SC1090,SC1091
. "$(dirname "$0")"/.nnn-plugin-helper
CTX=+

if type zoxide >/dev/null 2>&1; then
	if type fzf >/dev/null 2>&1; then
		entry="$(zoxide query -i --)"
	else
		printf "jump to : "
		read -r dir
		entry="$(zoxide query -- "$dir")"
	fi
else
	exit 1
fi

# Check for picker mode
if [ "$3" ]; then
	if [ "$entry" ]; then
		case "$entry" in
		/*) fullpath="$entry" ;;
		*) fullpath="$PWD/$entry" ;;
		esac
		if [ "-" = "$3" ]; then
			printf "%s\n" "$fullpath"
		else
			printf "%s\n" "$fullpath" >"$3"
		fi

		# Tell `nnn` to clear its internal selection
		printf "%s" "0p" >"$NNN_PIPE"
	fi

	exit 0
fi

# Open the selected folder in new tmux window
if [ -n "$entry" ]; then
	echo "**********************************************************"
	echo "> Selected folder: $entry\n"
	echo "Please choose the action to proceed:\n"
	echo "  1. Change to selected folder"
	echo "  2. Open in new tmux window"
	echo "  3. Open with LunarVim"
	echo "  4. Open with Lazygit"
	read -r -p "Action: " ans
	case $ans in
	2)
		tmux new-window -c "$entry"
		;;
	3)
		tmux new-window -n "lvim" -c "$entry" "lvim"
		;;
	4)
		tmux new-window -n "lazygit" -c "$entry" "lazygit"
		;;
	1|*)
		if [ -n "$entry" ]; then
			if [ "$entry" = "." ] || { ! [ -d "$entry" ] && ! [ -f "$entry" ]; }; then
				exit 0
			fi

			# Check if the selected path returned by fzf command is absolute
			case $entry in
			/*) nnn_cd "$entry" "$CTX" ;;
			*)
				# Remove "./" prefix if it exists
				sel="${sel#./}"

				if [ "$PWD" = "/" ]; then
					nnn_cd "/$entry" "$CTX"
				else
					nnn_cd "$PWD/$entry" "$CTX"
				fi
				;;
			esac
		fi
		;;
	esac
fi
